export const BioItemData = {
  questions: {
    createdAt: "তৈরীর তারিখ",
    updatedAt: "আপডেট তারিখ",
  },
  short: {
    label: "সংক্ষিপ্ত বায়োডাটা তথ্য",
    othersLabel: "আন্যান্য তথ্য",
  },
  general: {
    label: "সাধারন তথ্য",
    questions: {
      gender: "পাত্রের ধরন",
      marital_status: "বৈবাহিক অবস্থা",
      birth_date: "জন্মসন",
      complexion: "গাত্রবর্ণ",
      height: "উচ্চতা",
      weight: "ওজন",
      blood_group: "রক্তের গ্রুপ",
      language_skills: "ভাষা দক্ষতা",
    },
  },
  location: {
    label: "ঠিকানা",
    questions: {
      permanent_address: "স্থায়ী ঠিকানা",
      present_address: "বর্তমান ঠিকানা",
      relocate_plan: "স্থানান্তর পরিকল্পনা",
      childhood_address: "শৈশবের ঠিকানা",
    },
  },
  education: {
    label: "শিক্ষা",
    questions: {
      education_medium: "শিক্ষার মাধ্যম",
      current_study: "বর্তমান অধ্যয়নের বিষয়",
      highest_qualification: "সর্বোচ্চ শিক্ষাগত যোগ্যতা",
      previous_exams: "পূর্ববর্তী পরীক্ষা ও তার ফলাফল",
      other_qualifications: "অন্যান্য শিক্ষাগত যোগ্যতা",
    },
  },
  personal_info: {
    label: "ব্যাক্তিগত তথ্য",
    questions: {
      about_yourself: "নিজের সম্পর্কে বিস্তারিত",
      outdoor_clothing: "বাহিরে পরিধান করা পোশাকের ধরন",
      physical_mental_illness: "শারীরিক/মানসিক অসুস্থতা",
      favorite_books: "প্রিয় বই",
      favorite_online_personalities: "প্রিয় অনলাইন ব্যক্তিত্ব",
      device_usage_time: "মোবাইল ও কম্পিউটার ব্যবহারের সময় সম্পর্কে বিস্তারিত",
      affiliations:
        "ব্যক্তি বা তার পরিবার কোনো ধরনের দল, মত, বা কর্মকান্ডের সাথে যুক্ত থাকার বিষয়ে বিস্তারিত তথ্য।",
    },
  },
  family: {
    label: "পারিবারিক তথ্য",
    questions: {
      family_members_info: "পারিবারিক সদস্যদের তথ্য",
      uncles_info: "চাচা/মামার তথ্য",
      descent: "বংশ পরিচয়",
      economic_status: "আর্থিক অবস্থার বিস্তারিত",
    },
  },
  profession: {
    label: "পেশা",
    questions: {
      profession: "পেশা",
      profession_description: "পেশার বর্ণনা",
      monthly_income: "মাসিক আয়",
    },
  },
  religious: {
    label: "ধর্ম",
    questions: {
      prayer_habits: "নামাজের অভ্যাস",
      haram_relationships: "হারাম সম্পর্ক",
      quran_recitation: "কুরআন তেলাওয়াত",
      mahram_adherence: "মাহরাম পালনে নিষ্ঠা",
      has_beard: "দাড়ি রাখা",
      entertainment_habits: "বিনোদনের অভ্যাস",
      mazhab: "মাযহাব",
      religious_beliefs: "ধর্মীয় বিশ্বাস",
      religious_knowledge: "ধর্মীয় জ্ঞান",
      family_religious_environment: "পারিবারিক ধর্মীয় পরিবেশ",
    },
  },
  marriage_info: {
    label: "বৈবাহিক তথ্য",
    questions: {
      prev_marriage: "পূর্ববর্তী বিবাহ",
      work_after: "বিবাহের পর চাকরি করতে চান?",
      study_after: "বিবাহের পর পড়াশোনা চালিয়ে যেতে চান?",
      ceremony_plans: "বিবাহের অনুষ্ঠানের পরিকল্পনা",
      partner_view_rules: "পাত্র / পাত্রী দেখার নিয়ম",
      marriage_weakness: "নিজ পক্ষের দুর্বলতা",
      family_pref: "পরিবারের পছন্দ",
      compromise_factors: "ছাড় দেওয়ার বিষয়াবলি",
      dowry_amount: "মোহরানার পরিমাণ",
      dowry_opinion: "মোহরানা সম্পর্কে মতামত",
      cash_gift_opinion: "সমাজে প্রচলিত বিভিন্ন উপহার পাঠানো সম্পর্কে মতামত",
    },
  },
  expected_partner: {
    label: "প্রত্যাশিত জীবনসঙ্গী",
    questions: {
      age: "প্রত্যাশিত জীবনসঙ্গীর বয়স",
      height: "প্রত্যাশিত জীবনসঙ্গীর উচ্চতা",
      complexion: "প্রত্যাশিত জীবনসঙ্গীর গাত্রবর্ণ",
      marital_status: "প্রত্যাশিত জীবনসঙ্গীর বৈবাহিক অবস্থা",
      educational_qualification: "প্রত্যাশিত জীবনসঙ্গীর শিক্ষাগত যোগ্যতা",
      profession: "প্রত্যাশিত জীবনসঙ্গীর পেশা",
      economic_status: "প্রত্যাশিত জীবনসঙ্গীর আর্থিক অবস্থা",
      bio_profile_types: "প্রত্যাশিত জীবনসঙ্গীর প্রোফাইলের ধরন",
      family: "প্রত্যাশিত জীবনসঙ্গীর পারিবারিক অবস্থা",
      about_partner: "পছন্দের জীবনসঙ্গী সম্পর্কে বিস্তারিত",
    },
  },
  hidden: {
    label: "গোপনীয় তথ্য",
    questions: {
      name: "নাম",
      email: "ইমেইল",
      location: "ঠিকানা",
      family_members_name: "পরিবারের সদস্যদের নাম",
      current_parent: "বর্তমান অভিভাবক",
      parent_mobile: "অভিভাবকের মোবাইল নম্বর",
      social_links: "সামাজিক যোগাযোগ মাধ্যমের লিংক সমূহ",
      permanent_address_map_location: "স্থায়ী ঠিকানার মানচিত্রের অবস্থান",
      present_address_map_location: "বর্তমান ঠিকানার মানচিত্রের অবস্থান",
      documents_links: "ডকুমেন্ট লিংক",
    },
  },
};
